
#数据库连接配置
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/golden_crm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
  #  password: K35fBUzWzdf6
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  application:
    name: yelot_crm
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#mynatis配置
mybatis:
  type-aliases-package: com.yelot.crm.entity
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml
#加载log4j2

server:
  port: 8080
  session:
    timeout: 12000





